import Link from "next/link";
import { ArrowDown, ArrowRight, ShieldCheck, Sparkles, UserCheck } from "lucide-react";
import { Card } from "@/components/ui";
import { scenarioIds, scenarios } from "@/lib/scenario-presentation";

export default function Home() {
  return <main id="main" className="page-shell landing purchase-landing">
    <section className="hero"><div className="hero-copy"><div className="eyebrow"><span className="tiny-star">✳</span> YOUR INTENT. YOUR APPROVAL.</div><h1>Buy with<br />clarity.<br /><span>Stay in control.</span></h1><p className="hero-description">Floww는 구매 목적, 예산과 기한 안에서 후보를 검토합니다. 선택 견적과 판매처를 확인한 뒤 사용자가 직접 승인합니다.</p><div className="hero-actions"><Link href="/pharmacy" className="button primary">구매 시작 <ArrowRight size={19} /></Link><a className="text-link" href="#scenarios">세 가지 경우 보기 <ArrowDown size={16} /></a></div><div className="hero-note"><ShieldCheck size={16} /> 지갑 로그인과 구매 승인은 별개입니다.</div></div>
      <div className="hero-visual" aria-label="Floww 구매 조건"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="visual-star">✳</div><div className="floating-chip"><Sparkles size={17} /> A clear intent. A considered purchase.</div><Card className="preview-card"><div className="preview-top"><span className="mini-brand">floww</span><span className="tag">PURCHASE CONTROL</span></div><p className="label">예시 작업 한도</p><div className="preview-balance">60 <span>fUSDC</span></div><span className="positive performance"><ShieldCheck size={14} /> 최종 승인 전 지출 권한 없음</span><div className="preview-product"><span className="icon-tile"><UserCheck size={27} /></span><div><strong>약국 구매 요청</strong><p>품목 · 예산 · 기한 · 판매처</p></div></div><dl className="preview-prices"><div><dt>후보 견적</dt><dd>서버에서 확인</dd></div><div><dt>정책 결과</dt><dd>서버 검사 후 표시</dd></div><div><dt>구매 결과</dt><dd>영수증과 이행 확인 후 표시</dd></div></dl></Card></div></section>
    <section id="scenarios" className="scenario-home"><div className="section-heading"><div><span className="eyebrow">THREE PATHS · ONE CONTROL</span><h2>어떤 결과도 확인 전에는 확정하지 않습니다.</h2></div></div><div className="scenario-grid">{scenarioIds.map((id, index) => <Link className="scenario-card" href={`/pharmacy?scenario=${id}`} key={id}><span className="scenario-number">0{index + 1}</span><h3>{scenarios[id].title}</h3><p>{scenarios[id].summary}</p><span className="scenario-card-action">시나리오 열기 <ArrowRight size={17} /></span></Link>)}</div></section>
    <section className="bottom-cta"><div><span className="eyebrow">YOUR PURCHASE, YOUR CALL</span><h2>서버 기록으로 진행을 확인하세요.</h2><p>한 작업의 제안, 정책 판정, 승인, 지급과 이행을 이어서 확인할 수 있습니다.</p></div><Link href="/pharmacy" className="button primary">내 구매 시작 <ArrowRight size={18} /></Link></section>
  </main>;
}
